export enum actionTypes {
	TICK = 'TICK',
	CREATE_BOARD = 'CREATE_BOARD',
	CLEAR_BOARD = 'CLEAR_BOARD',
	SET_ALIVE = 'SET_ALIVE',
	MOUSE_DOWN = 'MOUSE_DOWN',
	MOUSE_UP = 'MOUSE_UP',
	START_GAME = 'START_GAME',
	PAUSE_GAME = 'PAUSE_GAME',

}
